import React, { useState } from 'react';
import { FileText, Share2, Copy, Check } from 'lucide-react';

function buildSummaryText(fields, result) {
  const lines = [
    "WEHA HEALTH - VISIT SUMMARY",
    "",
    `Date: ${new Date().toLocaleString()}`,
    `Symptom category: ${fields.symptom_category || 'not specified'}`,
    `Symptoms: ${(fields.symptoms || []).join(', ') || 'not specified'}`,
    `Duration: ${fields.duration || 'not specified'}`,
    `Severity: ${fields.severity || 'not specified'}`,
  ];
  if (fields.is_pregnant !== undefined && fields.is_pregnant !== null) {
    lines.push(`Pregnant: ${fields.is_pregnant}`);
  }
  lines.push(`Assessed urgency: ${result.urgency}`);
  if (result.matched_signs?.length > 0) {
    lines.push(`Danger signs noted: ${result.matched_signs.map(s => s.sign.replace('_', ' ')).join(', ')}`);
  }
  lines.push(`Guidance given: ${result.guidance}`);
  lines.push("");
  lines.push("This summary was generated by Weha Health, a voice-first health assistant. It is not a diagnosis. Please show this to a health worker.");
  return lines.join("\n");
}

export default function VisitSummary({ fields, result }) {
  const [copied, setCopied] = useState(false);
  const summaryText = buildSummaryText(fields, result);

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Weha Health Visit Summary',
          text: summaryText,
        });
        return;
      } catch (err) {
        // User cancelled or share failed — fall through to copy.
      }
    }
    handleCopy();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      // Clipboard blocked — nothing more we can do silently.
    }
  };

  return (
    <div className="rounded-xl border border-health-border bg-health-bg/40 p-4 mt-2">
      <div className="flex items-center gap-2 mb-2 text-health-textPrimary font-semibold text-sm">
        <FileText size={16} />
        <span>Visit Summary</span>
      </div>
      <pre className="whitespace-pre-wrap text-xs text-health-textSecondary leading-relaxed font-sans">
        {summaryText}
      </pre>
      <div className="flex gap-2 mt-3">
        <button
          onClick={handleShare}
          className="flex-1 flex items-center justify-center gap-2 text-xs font-medium py-2 rounded-lg bg-health-accent text-health-bg hover:bg-health-accentLight transition"
        >
          <Share2 size={14} />
          Share
        </button>
        <button
          onClick={handleCopy}
          className="flex-1 flex items-center justify-center gap-2 text-xs font-medium py-2 rounded-lg border border-health-border text-health-textSecondary hover:text-health-textPrimary transition"
        >
          {copied ? <Check size={14} /> : <Copy size={14} />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
    </div>
  );
}