import React, { useState } from 'react';
import { FileText, Share2, Copy, Check } from 'lucide-react';

const LABELS = {
  en: { date: "Date", category: "Symptom category", symptoms: "Symptoms", duration: "Duration", severity: "Severity", pregnant: "Pregnant", urgency: "Assessed urgency", dangerSigns: "Danger signs noted", guidance: "Guidance given", footer: "This summary was generated by Weha Health, a voice-first health assistant. It is not a diagnosis. Please show this to a health worker.", notSpecified: "not specified" },
  pcm: { date: "Date", category: "Symptom category", symptoms: "Symptoms", duration: "How long", severity: "How bad e be", pregnant: "Pregnant", urgency: "Wetin we see", dangerSigns: "Danger signs wey show", guidance: "Wetin to do", footer: "Weha Health generate this summary give you. E no be diagnosis. Abeg show am to health worker.", notSpecified: "no info" },
  yo: { date: "Ọjọ́", category: "Irú àìsàn", symptoms: "Àwọn àmì àìsàn", duration: "Ìgbà tó ti pé", severity: "Bí ó ṣe le tó", pregnant: "Aboyun", urgency: "Ìdíwọ̀n pàjáwìrì", dangerSigns: "Àwọn àmì ewu tí a rí", guidance: "Ìtọ́ni tí a fúnni", footer: "Weha Health ni ó ṣe àkọsílẹ̀ yìí. Kì í ṣe àyẹ̀wò dókítà. Jọ̀wọ́ fi hàn òṣìṣẹ́ ìlera.", notSpecified: "a kò sọ" },
  ak: { date: "Da", category: "Yare kwan", symptoms: "Nsɛnkyerɛnne", duration: "Bere a atwam", severity: "Sɛnea emu yɛ den", pregnant: "Onyinsɛn", urgency: "Ntɛm hia a wɔahu", dangerSigns: "Asiane nsɛnkyerɛnne a wohuu", guidance: "Afotuo a wɔde mae", footer: "Weha Health na ɛyɛɛ krataa yi. Ɛnyɛ oduruyɛfo nhwehwɛmu. Yɛsrɛ wo, kyerɛ ɔyaresafo.", notSpecified: "wɔanka" },
  am: { date: "ቀን", category: "የምልክት ምድብ", symptoms: "ምልክቶች", duration: "ቆይታ", severity: "ክብደት", pregnant: "እርጉዝ", urgency: "የተገመገመ አስቸኳይነት", dangerSigns: "የተስተዋሉ የአደጋ ምልክቶች", guidance: "የተሰጠ መመሪያ", footer: "ይህ ማጠቃለያ በWeha Health ተፈጥሯል። ይህ ምርመራ አይደለም። እባክዎ ለጤና ባለሙያ ያሳዩ።", notSpecified: "አልተገለጸም" },
};

function buildSummaryText(fields, result, language) {
  const t = LABELS[language] || LABELS.en;

  const lines = [
    "WEHA HEALTH",
    "",
    `${t.date}: ${new Date().toLocaleString()}`,
    `${t.category}: ${fields.symptom_category || t.notSpecified}`,
    `${t.symptoms}: ${(fields.symptoms || []).join(', ') || t.notSpecified}`,
    `${t.duration}: ${fields.duration || t.notSpecified}`,
    `${t.severity}: ${fields.severity || t.notSpecified}`,
  ];
  if (fields.is_pregnant !== undefined && fields.is_pregnant !== null) {
    lines.push(`${t.pregnant}: ${fields.is_pregnant}`);
  }
  lines.push(`${t.urgency}: ${result.urgency}`);
  if (result.matched_signs?.length > 0) {
    lines.push(`${t.dangerSigns}: ${result.matched_signs.map(s => s.sign.replace('_', ' ')).join(', ')}`);
  }
  lines.push(`${t.guidance}: ${result.guidance}`);
  lines.push("");
  lines.push(t.footer);
  return lines.join("\n");
}

export default function VisitSummary({ fields, result, language = 'en' }) {
  const [copied, setCopied] = useState(false);
  const summaryText = buildSummaryText(fields, result, language);

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Weha Health Visit Summary', text: summaryText });
        return;
      } catch (err) {
        // fall through to copy
      }
    }
    handleCopy();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      // clipboard blocked, nothing more to do silently
    }
  };

  return (
    <div className="rounded-xl border border-health-border bg-health-bg/40 p-4 mt-2">
      <div className="flex items-center gap-2 mb-2 text-health-textPrimary font-semibold text-sm">
        <FileText size={16} />
        <span>Visit Summary</span>
      </div>
      <pre className="whitespace-pre-wrap text-xs text-health-textSecondary leading-relaxed font-sans">
        {summaryText}
      </pre>
      <div className="flex gap-2 mt-3">
        <button
          onClick={handleShare}
          className="flex-1 flex items-center justify-center gap-2 text-xs font-medium py-2 rounded-lg bg-health-accent text-health-bg hover:bg-health-accentLight transition"
        >
          <Share2 size={14} />
          Share
        </button>
        <button
          onClick={handleCopy}
          className="flex-1 flex items-center justify-center gap-2 text-xs font-medium py-2 rounded-lg border border-health-border text-health-textSecondary hover:text-health-textPrimary transition"
        >
          {copied ? <Check size={14} /> : <Copy size={14} />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
    </div>
  );
}